production:
  solr:
    hostname: localhost
    path: /solr/code
    port: 8080
    log_level: WARNING

development:
  solr:
    hostname: 85.214.238.131
    path: /solr/code
    port: 8080
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING