production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: 83.150.206.154
    path: /solr/code
    port: 8080
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING